### ISSUE TITLE
React/RCTBundleURLProvider.h' file not found

### ISSUE THREAD

**Issue by ahtisham09** [shaneosullivan/ReactNativeExampleBrowserExtension#1]
Hey @shaneosullivan i am trying to add Action Extension but i am getting this Error Project version is V0.63.4 when i add the React/RCTBundleURLProvider.h and i got this error Please help me to solve this issue Thanks

<img width="1046" alt="Screenshot 2021-08-05 at 2 28 57 PM" src="https://user-images.githubusercontent.com/59255791/128374135-636d2f46-9930-44aa-85c6-4c3f7705da0d.png">

**Comment by ahtisham09** [comment]
<img width="1046" alt="Screenshot 2021-08-05 at 2 28 57 PM" src="https://user-images.githubusercontent.com/59255791/128374076-ea15ad97-0109-45eb-91a8-5395103e1217.png">

**Comment by Saisharanvemu** [comment]
Hey @ahtisham09  I am getting the same error...Could you please let me know how to resolve this issue. Thanks :)
